name: Publish
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      NODE_ENV: development
    steps:
      - name: Change user
        run: sudo chown -R $USER:$USER ${{ github.workspace }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
      - name: Create release info
        run: |
          echo "${{ steps.current-time.outputs.year }}.${{ steps.current-time.outputs.month }}.${{ steps.current-time.outputs.day }}.$GITHUB_RUN_NUMBER" > ./release.txt
      - name: Upload workspace
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            src
            Dockerfile
            package.json
            package-lock.json
            release.txt
  push:
    runs-on: ubuntu-20.04
    env:
      NODE_ENV: development
    needs: [build]
    env:
      DOCKER_IMAGE: educandu/backup-restore-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Set RELEASE_NUMBER
        run: echo "RELEASE_NUMBER="$(cat ./dist/release.txt | tr -d '\n')"" >> $GITHUB_ENV
      - name: Create release notes
        run: echo "RELEASE_NOTES=$(echo $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/commit/$GITHUB_SHA)" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ env.RELEASE_NUMBER }}
            ${{ env.DOCKER_IMAGE }}:latest
